### ISSUE TITLE
Http 500 error when querying the Gaia catalog through Vizier

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#112]
The following error occurs in vizier_utils.py when querying Vizier for Gaia catalog objects within the field of view of a reference image, but only for some datasets:

500 Error 500:
null
Traceback (most recent call last):
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-macosx-10.14-x86_64.egg/pyDANDIA/vizier_tools.py", line 71, in search_vizier_for_gaia_sources
    qs = Gaia.cone_search_async(c, r)
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/astroquery/gaia/core.py", line 474, in cone_search_async
    dump_to_file=dump_to_file, columns=columns)
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/astroquery/gaia/core.py", line 365, in __cone_search
    background=background)
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/astroquery/utils/tap/core.py", line 443, in launch_job_async
    job.get_results()
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/astroquery/utils/tap/model/job.py", line 247, in get_results
    self.__load_async_job_results()
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/astroquery/utils/tap/model/job.py", line 344, in __load_async_job_results
    200)
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/astroquery/utils/tap/conn/tapconn.py", line 635, in check_launch_response_status
    raise requests.exceptions.HTTPError(errMsg)
requests.exceptions.HTTPError: Error 500:
null

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reduction_control.py", line 552, in <module>
    reduction_control()
  File "reduction_control.py", line 75, in reduction_control
    run_automatic_reduction(setup,red_log,params)
  File "reduction_control.py", line 264, in run_automatic_reduction
    status = run_new_reduction(setup, config, red_log)
  File "reduction_control.py", line 294, in run_new_reduction
    'reference astrometry', setup, status, red_log, **config)
  File "reduction_control.py", line 394, in execute_stage
    (status, report) = run_stage_func(setup, **kwargs)
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-macosx-10.14-x86_64.egg/pyDANDIA/reference_astrometry.py", line 98, in run_reference_astrometry
    stellar_density_threshold)
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-macosx-10.14-x86_64.egg/pyDANDIA/reference_astrometry.py", line 349, in catalog_objects_in_reference_image
    image_wcs,log,'Gaia')
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-macosx-10.14-x86_64.egg/pyDANDIA/wcs.py", line 154, in fetch_catalog_sources_for_field
    log=log)
  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-macosx-10.14-x86_64.egg/pyDANDIA/vizier_tools.py", line 79, in search_vizier_for_gaia_sources
    raise requests.exceptions.HTTPError()
requests.exceptions.HTTPError

**Comment by rachel3834** [comment]
This bug appears to be the result of issues at the ESA server, which are unspecified in the error message, which cause it to fail to respond to the query.  The only solution is for our pipeline to be able to handle this occurring. 

There are alternative servers for the Gaia data, so I have implemented code (based on similar code from NEOExchange, thanks to Tim Lister), to query a list of alternative catalog servers, to provide a failsafe for the pipeline.   Testing this code now.

**Comment by rachel3834** [comment]
New code has resolved this issue.
