### ISSUE TITLE
HDUList bug stage 4

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#124]
Pipeline crashes at stage 4 with the following error:
Traceback (most recent call last):
  File "/data/robouser/software/pyDANDIA/pyDANDIA/reduction_control.py", line 745, in <module>
    reduction_control()
  File "/data/robouser/software/pyDANDIA/pyDANDIA/reduction_control.py", line 83, in reduction_control
    run_automatic_reduction(setup,red_log,params)
  File "/data/robouser/software/pyDANDIA/pyDANDIA/reduction_control.py", line 279, in run_automatic_reduction
    status = run_existing_reduction(setup, config, red_log)
  File "/data/robouser/software/pyDANDIA/pyDANDIA/reduction_control.py", line 297, in run_existing_reduction
    status = execute_stage(stage4.run_stage4, 'stage 4', setup, status, red_log)
  File "/data/robouser/software/pyDANDIA/pyDANDIA/reduction_control.py", line 582, in execute_stage
    (status, report) = run_stage_func(setup, **kwargs)
  File "/data/robouser/software/robonet_venv3/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage4.py", line 224, in run_stage4
    image_red_status, log=log, mask_extension_in=-1)
  File "/data/robouser/software/robonet_venv3/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage4.py", line 718, in resample_image_stamps
    mask_image = np.array(data_image_hdu[image_structure['pyDANDIA_pixel_mask']].data, dtype=float)
  File "/data/robouser/software/robonet_venv3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 300, in __getitem__
    self._positive_index_of(key))
  File "/data/robouser/software/robonet_venv3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 754, in _positive_index_of
    index = self.index_of(key)
  File "/data/robouser/software/robonet_venv3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 719, in index_of
    ''.format(self.__class__.__name__, _key))
KeyError: 'HDUList indices must be integers, extension names as strings, or (extname, version) tuples; got None'

**Comment by rachel3834** [comment]
This issue was caused by an image which was missing the pyDANDIA bad pixel mask in the FITS image structure.  This caused the image handling routine to return None rather than the index of the BPM in the FITS HDU list.  

I've fixed this issue by adding exception handling for this case.
