### ISSUE TITLE
stage4 crashes at image resampling

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#127]
Traceback (most recent call last):
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage4.py", line 865, in resample_image_stamps
    img = img-bkg
ValueError: operands could not be broadcast together with shapes (1010,1010) (958,991) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reduction_control.py", line 750, in <module>
    reduction_control()
  File "reduction_control.py", line 71, in reduction_control
    run_image_analysis(setup,red_log,params)
  File "reduction_control.py", line 127, in run_image_analysis
    status = execute_stage(stage4.run_stage4, 'stage 4', setup, status, red_log)
  File "reduction_control.py", line 587, in execute_stage
    (status, report) = run_stage_func(setup, **kwargs)
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage4.py", line 225, in run_stage4
    image_red_status, log=log, mask_extension_in=-1)
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage4.py", line 904, in resample_image_stamps
    model_stamp = tf.SimilarityTransform(translation=(-shifts[1],-shifts[0]))
UnboundLocalError: local variable 'shifts' referenced before assignment

**Comment by rachel3834** [comment]
This issue appears to have crashed the majority of the ROME-01 re-reductions.  For an example dataset, see einstore:/data02/rstreet/data_reduction/ROME-FIELD-01/ROME-FIELD-01_lsc-doma-1m0-05-fa15_ip

**Comment by rachel3834** [comment]
This issue was addressed by Etienne, who reviewed the merging of the omega-realtime-master and ROME-DR1 branches and found it was incomplete.  The merge was completed and tested under branch FixMergeBranches, and found to be working.
