### ISSUE TITLE
Stage6 crash when storing photometry in data array

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#128]
My test-run of the updated FixMergeBranches branch completed stages 4 and 5 OK but crashed in stage6 with the following error - looks like an indexing issue when the stamp photometry is transferred to the main array for full-frame output: 

/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
Traceback (most recent call last):
  File "/home/rstreet/software/pyDANDIA/pyDANDIA/reduction_control.py", line 750, in <module>
    reduction_control()
  File "/home/rstreet/software/pyDANDIA/pyDANDIA/reduction_control.py", line 71, in reduction_control
    run_image_analysis(setup,red_log,params)
  File "/home/rstreet/software/pyDANDIA/pyDANDIA/reduction_control.py", line 131, in run_image_analysis
    status = execute_stage(stage6.run_stage6, 'stage 6', setup, status, red_log, **params)
  File "/home/rstreet/software/pyDANDIA/pyDANDIA/reduction_control.py", line 587, in execute_stage
    (status, report) = run_stage_func(setup, **kwargs)
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage6.py", line 288, in run_stage6
    new_image, log, kwargs)
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage6.py", line 1175, in store_stamp_photometry_to_array
    photometry_data[star_dataset_index,image_dataset_index,0] = star_field_ids
IndexError: index 298 is out of bounds for axis 1 with size 22

**Comment by rachel3834** [comment]
OK, this is not a bug in the pipeline.  
This reduction was being run on a subset of frames from a larger dataset, but without re-reducing the dataset independently.  Stage6 uses the number of images in the data directory to gauge how big the photometry HDF array needs to be, but these index numbers were not the same as the frames in the metadata frames list, which is used to determine where in the array data should be stored.  

The solution to this would simply be to reprocess the dataset so that the metadata correctly represents the dataset.
