### ISSUE TITLE
branch:old_ref_astro pipeline fails at reference_astrometry

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#165]
After stage 2 and before stage 3 is executed, reference astrometry must be run on the reference image.

Command executed: `$ python run_stage.py reference_astrometry /home/ytsapras/MicrolensingHandbook/Images/OB170924/ /home/ytsapras/MicrolensingHandbook/Images/OB170924/reduction.db`

The call fails with the following error message:

> Traceback (most recent call last):
>   File "/home/ytsapras/MicrolensingHandbook/Images/OB170924/run_stage.py", line 272, in <module>
>     run_stage_stand_alone()
>   File "/home/ytsapras/MicrolensingHandbook/Images/OB170924/run_stage.py", line 68, in run_stage_stand_alone
>     (status, report) = new_reference_astrometry.run_reference_astrometry(setup,
>   File "/home/ytsapras/Installed_Programs/anaconda3/envs/pyDANDIAbook/lib/python3.10/site-packages/pyDANDIA-0.1-py3.10-linux-x86_64.egg/pyDANDIA/new_reference_astrometry.py", line 105, in run_reference_astrometry
>     gaia_sources = catalog_objects_in_reference_image(setup, header,
>   File "/home/ytsapras/Installed_Programs/anaconda3/envs/pyDANDIAbook/lib/python3.10/site-packages/pyDANDIA-0.1-py3.10-linux-x86_64.egg/pyDANDIA/new_reference_astrometry.py", line 396, in catalog_objects_in_reference_image
>     gaia_sources = wcs.fetch_catalog_sources_for_field(setup, field, header,
>   File "/home/ytsapras/Installed_Programs/anaconda3/envs/pyDANDIAbook/lib/python3.10/site-packages/pyDANDIA-0.1-py3.10-linux-x86_64.egg/pyDANDIA/**wcs.py", line 129, in fetch_catalog_sources_for_field**
>     if catalog_sources != None:
>   File "/home/ytsapras/Installed_Programs/anaconda3/envs/pyDANDIAbook/lib/python3.10/site-packages/astropy/table/table.py", line 3695, in __ne__
>     return ~self.__eq__(other)
>   File "/home/ytsapras/Installed_Programs/anaconda3/envs/pyDANDIAbook/lib/python3.10/site-packages/astropy/table/table.py", line 3692, in __eq__
>     return self._rows_equal(other)
>   File "/home/ytsapras/Installed_Programs/anaconda3/envs/pyDANDIAbook/lib/python3.10/site-packages/astropy/table/table.py", line 3740, in _rows_equal
>     result = self.as_array() == other
> TypeError: Cannot compare structured or void to non-void arrays.

Log output:
[reference_astrometry.log](https://github.com/pyDANDIA/pyDANDIA/files/12664667/reference_astrometry.log)

**Comment by ytsapras** [comment]
This problem did not arise again when I restarted the reduction and chose a different reference, so I am closing it.
