### ISSUE TITLE
Stage3 crashing on SBIG

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#69]
Stage3 now well passes the wcs but I obtained this bug :

Traceback (most recent call last):
  File "run_stage.py", line 139, in <module>
    run_stage_stand_alone()
  File "run_stage.py", line 60, in run_stage_stand_alone
    (status, report) = stage3.run_stage3(setup)
  File "/home/ebachelet/.local/lib/python3.6/site-packages/pyDANDIA-0.1-py3.6-linux-x86_64.egg/pyDANDIA/stage3.py", line 71, in run_stage3
    reduction_metadata,log,ref_star_catalog)
  File "/home/ebachelet/.local/lib/python3.6/site-packages/pyDANDIA-0.1-py3.6-linux-x86_64.egg/pyDANDIA/sky_background.py", line 38, in model_sky_background
    diagnostics=True)
  File "/home/ebachelet/.local/lib/python3.6/site-packages/pyDANDIA-0.1-py3.6-linux-x86_64.egg/pyDANDIA/sky_background.py", line 180, in mask_stars
    psf_mask[py1:py2,px1:px2]
ValueError: operands could not be broadcast together with shapes (9,10) (9,17)

**Comment by ytsapras** [comment]
Is this still a problem? If it is fixed, please close the issue.
