### ISSUE TITLE
Stag6 foreing key issue

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#70]
Here is the db issue I get after the photometry is done an all the difference images

Traceback (most recent call last):
  File "run_stage.py", line 135, in <module>
    run_stage_stand_alone()
  File "run_stage.py", line 72, in run_stage_stand_alone
    (status, report) = stage6.run_stage6(setup)
  File "/home/etienne/.local/lib/python3.5/site-packages/pyDANDIA-0.1-py3.5-linux-x86_64.egg/pyDANDIA/stage6.py", line 236, in run_stage6
    ingest_photometric_table_in_db(setup, exposures_id, star_indexes, photometric_table)
  File "/home/etienne/.local/lib/python3.5/site-packages/pyDANDIA-0.1-py3.5-linux-x86_64.egg/pyDANDIA/stage6.py", line 629, in ingest_photometric_table_in_db
    db_ai.load_astropy_table(conn, 'phot', new_table)
  File "/home/etienne/.local/lib/python3.5/site-packages/pyDANDIA-0.1-py3.5-linux-x86_64.egg/pyDANDIA/astropy_interface.py", line 23, in load_astropy_table
    [tuple(r) for r in table])
  File "/home/etienne/.local/lib/python3.5/site-packages/pyDANDIA-0.1-py3.5-linux-x86_64.egg/pyDANDIA/phot_db.py", line 220, in feed_to_table_many
    tuples)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

**Comment by ytsapras** [comment]
There were a few problems with the tests I run:
1) The database did not contain entries for exposures, reference_images or stars. These should exist before adding any photometry.
2) The database starts counting from 1, so index 0 will always return an IndexError. 
3) enumerate() will always start counting from 0 (so it won't work).

When adding new data, the code must pass the exposure_id and star_id as parameters, or in the case multiple entries as submitted, as tuples. If these are not known, the DB can be queried to obtain them.

**Comment by ytsapras** [comment]
Ingestion seems now to be normal so I am closing this. Reopen if there are further issues.
