### ISSUE TITLE
stage3 crashes after psf_fit

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#71]
Hello

Here is a new crashes I had after the psf_fits : 
-> companion star too close to the stamp edge to model
 -> Parameters of fitted PSF model: [36294430.97212602, 4.014854640100898, 4.023437660059891, 3.7049468656864253, 4.175644963095151]
Applying Moffat2D PSF of diameter=3.0
Scaling fluxes by exposure time 120.0s
 -> Star 0 at position (70.20949935577484, 0.276184762359035)
0th PSF Star at (70.20949935577484, 0.276184762359035) has stamp x,y ranges: (67, 73, 0, 3)
 -> Star 0 fitted model parameters = [643.9001858462184, 0.276184762359035, 70.20949935577484, 3.7049468656864253, 4.175644963095151] good fit? True
Traceback (most recent call last):
  File "run_stage.py", line 139, in <module>
    run_stage_stand_alone()
  File "run_stage.py", line 60, in run_stage_stand_alone
    (status, report) = stage3.run_stage3(setup)
  File "/home/ebachelet/.local/lib/python3.6/site-packages/pyDANDIA-0.1-py3.6-linux-x86_64.egg/pyDANDIA/stage3.py", line 98, in run_stage3
    centroiding=False)
  File "/home/ebachelet/.local/lib/python3.6/site-packages/pyDANDIA-0.1-py3.6-linux-x86_64.egg/pyDANDIA/photometry.py", line 102, in run_psf_photometry
    psf_size, psf_size)
ValueError: too many values to unpack (expected 2)

**Comment by ytsapras** [comment]
Is this still a problem? Close if not.
