### ISSUE TITLE
Stage 5 indexing error

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#80]
Running stage 5 on the dataset:
/data01/rstreet/data_reduction/proc/ROME-FIELD-16_lsc-doma-1m0-05-fa15_rp

It exited showing an index error in the construction of the quality control arrays that suggests there may be a mis-indexing problem at this point.  

Error output:
Constructing quality metrics columns in metadata
Traceback (most recent call last):
  File "run_stage.py", line 167, in <module>
    run_stage_stand_alone()
  File "run_stage.py", line 86, in run_stage_stand_alone
    (status, report) = stage5.run_stage5(setup)
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage5.py", line 174, in run_stage5
    sorted_data[row_index] = quality_metrics[index]
IndexError: index 142 is out of bounds for axis 0 with size 142

**Comment by rachel3834** [comment]
This issue was caused by the function subtract_with_constant_kernel, which constructs the quality_metrics array one image at a time.  It has a try:...except: clause, and the exception section did not add a null entry to this array for any images where the subtraction failed for whatever reason.  
This meant that for larger datasets, which have a higher likelihood of containing one or more poor-quality images, the quality_metrics array ended up with fewer entries that the full list of images in the dataset, resulting in the indexing error above.  

I believe I've fixed this issue by adding a null entry to the quality_metrics array for images which trigger the exception.
