### ISSUE TITLE
stage 5 numpy ValueError (in format.py)

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#86]
Hi all,
When running stage 5 on Einstore I get the following ValueError message:
Traceback (most recent call last):
  File "run_stage.py", line 193, in <module>
    run_stage_stand_alone()
  File "run_stage.py", line 87, in run_stage_stand_alone
    (status, report) = stage5.run_stage5(setup)
  File "/home/.../anaconda3/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage5.py", line 179, in run_stage5
    quality_metrics = subtract_with_constant_kernel(new_images, reference_image_name, reference_image_directory, reduction_metadata, setup, data_image_directory, kernel_size_array, max_adu, ref_stats, maxshift, kernel_directory_path, diffim_directory_path, log)
  File "/home/.../anaconda3/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/stage5.py", line 349, in subtract_with_constant_kernel
    umatrices, kernel_sizes, max_adu_restored = np.load(os.path.join(kernel_directory_path,'unweighted_u_matrix.npy'))
  File "/home/.../anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/.../anaconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

Is this something you have encountered before? It happens right at the end and the stage seems to complete, but with no additional information given.

**Comment by ebachelet** [comment]
Which numpy are you using? i.e. 
https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa/56062555

**Comment by ytsapras** [comment]
1.16.4
