### ISSUE TITLE
Ref astro crashes in skimage 

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#97]
Traceback (most recent call last):
  File "run_stage.py", line 210, in <module>
    run_stage_stand_alone()
  File "run_stage.py", line 70, in run_stage_stand_alone
    trust_wcs=params['trust_wcs'])
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/reference_astrometry.py", line 228, in run_reference_astrometry
    log)
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-linux-x86_64.egg/pyDANDIA/calc_coord_offsets.py", line 340, in calc_world_transform
    residual_threshold=2, max_trials=100)
  File "/home/rstreet/software/pydandia-venv/lib/python3.7/site-packages/skimage/measure/fit.py", line 807, in ransac
    random_idxs = random_state.randint(0, num_samples, min_samples)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high

**Comment by rachel3834** [comment]
This issue occurs in the code which is attempting to refine the WCS solution, which has a number of entry points depending on the state and nature of the data.  Normally it would iteratively try to match the catalog to the detected stars and calculate a refined coordinate transformation.  This error is occuring because somehow the code is not iterating properly for certain restricted circumstances, and proceeding with the next step of the algorithm before it has identified a set of cross-matched stars, causing it to crash.  

The circumstances under which this occurs seems to be where the initial WCS fit is sufficiently good that the histogram method is ineffective, triggering a clause in the code which is little used for Bulge data where the initial WCS fit is usually problematic.  Hence the issue has been seen in reductions of data for Gaia events but rarely in the ROME data processing.  

I have re-arranged this section of the WCS code to enforce the different clauses properly and I'm testing this now.  This section of the code will be a candidate for re-factoring for v2.0.

**Comment by rachel3834** [comment]
The re-arranged code appears to resolve this issue.
